inherit_from: .rubocop_todo.yml

Style/IndentArray:
  EnforcedStyle: consistent
Style/MethodName:
  EnforcedStyle: snake_case
Style/SymbolArray:
  EnforcedStyle: brackets
Lint/HandleExceptions:
  Exclude:
    - 'spec/palletjack-tool_spec.rb'
